### ISSUE TITLE
Loading a revision doesn't always set readyToInteract(true)

### ISSUE THREAD

**Issue by pdavis68** [wm-pxel/langchain-testbench#26]
When loading a chain, it doesn't always enable the Interact button. 

I don't have steps to reproduce this yet. It will take some tinkering to find out what steps are needed to reproduce it.

**Comment by acruikshank-wm** [comment]
This is a more complicated story. We need to rework how we calculate this. The chain that we store in the context gets updated when we add or delete chain specs, so it isn't sufficient to compare the chainSpec and the dirtyChainSpec. This strategy still works, but we may need a third tree to compare against.
